#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
### Powered by Alpine Linux ###

## Info ##

OS: Alpine
Always based on latest alpine-base@edge (http://nl.alpinelinux.org/alpine)

Rebuild every week.

## Thies88 ##
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
